---
apiVersion: v1
kind: Secret
metadata:
  name: bertobert-bertobert-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/bertobert-frontend-gitops
